# Generated by Django 2.2.5 on 2019-09-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('gene_id',),
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(max_length=20, verbose_name='Transcript-ID')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='annotation.Gene', verbose_name='Gene-ID')),
            ],
            options={
                'ordering': ('tr_id',),
            },
        ),
        migrations.CreateModel(
            name='GeneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_biotype', models.CharField(max_length=28)),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_type', to='annotation.Gene')),
            ],
            options={
                'ordering': ('gene_id',),
            },
        ),
        migrations.CreateModel(
            name='GeneNeighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBest', models.IntegerField()),
                ('lncRNA_transcript', models.CharField(max_length=50)),
                ('partnerRNA_transcript', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=9)),
                ('generic_type', models.CharField(max_length=10)),
                ('distance', models.IntegerField()),
                ('subtype', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=10)),
                ('lncRNA_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_neighbor', to='annotation.Gene')),
                ('partnerRNA_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_gene', to='annotation.Gene')),
            ],
            options={
                'ordering': ('partnerRNA_transcript', 'distance'),
            },
        ),
        migrations.CreateModel(
            name='GeneExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tissue', models.CharField(max_length=20)),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_exp', to='annotation.Gene', verbose_name='Gene-ID')),
            ],
            options={
                'ordering': ('gene_id',),
            },
        ),
        migrations.CreateModel(
            name='FunctionAnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_repr', models.IntegerField(verbose_name='Is-Repr')),
                ('blast_hit', models.CharField(max_length=50, verbose_name='Blast-Hit-Accession')),
                ('description', models.CharField(max_length=250, verbose_name='Human-Readable-Description')),
                ('pfam', models.CharField(max_length=250, verbose_name='Pfam-IDs-(Description)')),
                ('interpro', models.CharField(max_length=250, verbose_name='Interpro-IDs-(Description)')),
                ('go', models.CharField(max_length=250, verbose_name='GO-IDs-(Description)-via-Interpro')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function', to='annotation.Gene', verbose_name='Gene-ID')),
                ('tr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function', to='annotation.Transcript', verbose_name='Transcript-ID')),
            ],
            options={
                'ordering': ('tr_id',),
            },
        ),
    ]
