# Generated by Django 2.2.5 on 2019-09-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneneighbor',
            name='lncRNA_transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_neighbor', to='annotation.Transcript'),
        ),
        migrations.AlterField(
            model_name='geneneighbor',
            name='partnerRNA_transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_tr', to='annotation.Transcript'),
        ),
    ]
