# Generated by Django 2.2.5 on 2019-09-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_geneloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneloc',
            name='feature',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='geneloc',
            name='gene_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='annotation.Gene'),
        ),
        migrations.AlterField(
            model_name='geneloc',
            name='seqname',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='geneloc',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='annotation.Transcript'),
        ),
        migrations.CreateModel(
            name='GeneSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=4)),
                ('seq_index', models.IntegerField()),
                ('seq', models.CharField(max_length=60)),
                ('tr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='annotation.Transcript')),
            ],
            options={
                'ordering': ('tr_id', 'feature', 'seq_index'),
            },
        ),
    ]
