# Generated by Django 2.2.5 on 2019-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20190918_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneneighbor',
            name='pcc',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geneneighbor',
            name='pcc_pva',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
